services:
  - type: web
    name: fixmyresume
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libmagic1
      pip install -r backend/requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fixmyresume-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: fixmyresume-db
    databaseName: fixmyresume
    user: fixmyresume_user
