services:
  - type: web
    name: fixmyresume-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: fixmyresume-db
          property: connectionString

databases:
  - name: fixmyresume-db
    databaseName: fixmyresume
    user: fixmyresume 