services:
  - type: web
    name: fixmyresume-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: fixmyresume.onrender.com,fix-my-resume.vercel.app